# Generated by Django 5.2.7 on 2025-10-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=15)),
                ('nim', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
