# Generated by Django 5.2.6 on 2025-10-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kaprodi', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(max_length=100)),
                ('hari', models.CharField(max_length=20)),
                ('sks', models.IntegerField()),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('imagephoto', models.ImageField(upload_to='photos/')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.kuliah')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.siswa')),
            ],
        ),
    ]
