# Generated by Django 5.2.7 on 2025-11-04 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuliah',
            name='prodi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuliahs', to='quickstart.prodi'),
        ),
    ]
