# Generated by Django 5.2.6 on 2025-10-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='nama',
            new_name='nama_nasabah',
        ),
    ]
