# Generated by Django 5.2.6 on 2025-10-15 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0002_rename_nama_buku_nama_nasabah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('jemis', models.CharField(choices=[('debit', 'Debit'), ('kredit', 'Kredit')], max_length=10)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabungan.buku')),
            ],
        ),
    ]
