# Generated by Django 5.2.6 on 2025-10-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0003_transaksi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='jemis',
            new_name='jenis',
        ),
    ]
